version: "3"

services:
  broker-service:
    build:
      context: ./broker
    environment:
      - PORT=80
    restart: unless-stopped
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
